apiVersion: v1
kind: Pod
metadata:
  name: pod-user-25
  labels:
    version: "1"
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      volumeMounts:
      - name: htmldir
        mountPath: /usr/share/nginx/html
        readOnly: true
    - name: busybox
      image: busybox:latest
      command:
        - watch
        - echo 'Version 1' > /tmp/index.html
      volumeMounts:
      - name: htmldir
        mountPath: /tmp
  volumes:
    - name: htmldir
      emptyDir: {}
